In [ ]:
!kaggle competitions download -c house-prices-advanced-regression-techniques

from zipfile import ZipFile
import os
for i in os.listdir('C:/Users/mehmu/Desktop/PyProjects/Projects/Unlocked/KaggleComp/KaggleHouse'):
    if '.zip' in i:
        print(i)
        with ZipFile(i, 'r') as zipObj:
            zipObj.extractall()
        os.remove(i)

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import scipy as sc

df=pd.read_csv('train.csv')
df_test=pd.read_csv('test.csv')
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [2]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

## 1. DATA KONTROLÜ

In [3]:
df.columns[df.isnull().sum(axis=0)>0]

Index(['LotFrontage', 'Alley', 'MasVnrType', 'MasVnrArea', 'BsmtQual',
       'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Electrical', 'FireplaceQu', 'GarageType', 'GarageYrBlt',
       'GarageFinish', 'GarageQual', 'GarageCond', 'PoolQC', 'Fence',
       'MiscFeature'],
      dtype='object')

In [4]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)

              Total   Percent
PoolQC         1453  0.995205
MiscFeature    1406  0.963014
Alley          1369  0.937671
Fence          1179  0.807534
FireplaceQu     690  0.472603
LotFrontage     259  0.177397
GarageYrBlt      81  0.055479
GarageCond       81  0.055479
GarageType       81  0.055479
GarageFinish     81  0.055479
GarageQual       81  0.055479
BsmtFinType2     38  0.026027
BsmtExposure     38  0.026027
BsmtQual         37  0.025342
BsmtCond         37  0.025342
BsmtFinType1     37  0.025342
MasVnrArea        8  0.005479
MasVnrType        8  0.005479
Electrical        1  0.000685
Id                0  0.000000

In [5]:
na=['PoolQC','Alley','BsmtQual','BsmtCond','BsmtExposure','BsmtFinType1','BsmtFinType2','FireplaceQu','GarageType','GarageFinish',
'GarageQual','GarageCond','Fence','MiscFeature']
for i in na:
    df[i].replace(np.nan,'None',inplace=True)
    df_test[i].replace(np.nan,'None',inplace=True)

In [6]:
total = df.isnull().sum().sort_values(ascending=False)
percent = (df.isnull().sum()/df.isnull().count()).sort_values(ascending=False)
missing_data = pd.concat([total, percent], axis=1, keys=['Total', 'Percent'])
missing_data.head(20)

              Total   Percent
LotFrontage     259  0.177397
GarageYrBlt      81  0.055479
MasVnrType        8  0.005479
MasVnrArea        8  0.005479
Electrical        1  0.000685
KitchenQual       0  0.000000
GarageType        0  0.000000
FireplaceQu       0  0.000000
Fireplaces        0  0.000000
Functional        0  0.000000
TotRmsAbvGrd      0  0.000000
Id                0  0.000000
GarageFinish      0  0.000000
BedroomAbvGr      0  0.000000
HalfBath          0  0.000000
FullBath          0  0.000000
BsmtHalfBath      0  0.000000
BsmtFullBath      0  0.000000
GrLivArea         0  0.000000
LowQualFinSF      0  0.000000

In [7]:
df.nunique()

Id               1460
MSSubClass         15
MSZoning            5
LotFrontage       110
LotArea          1073
                 ...
MoSold             12
YrSold              5
SaleType            9
SaleCondition       6
SalePrice         663
Length: 81, dtype: int64

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          1460 non-null   object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1460 non-null   object
 31  BsmtCond       1460 non-null   object
 32  BsmtExposure   1460 non-null   object
 33  BsmtFinType1   1460 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1460 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    1460 non-null   object
 58  GarageType     1460 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1460 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1460 non-null   object
 64  GarageCond     1460 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         1460 non-null   object
 73  Fence          1460 non-null   object
 74  MiscFeature    1460 non-null   object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [9]:
#df['MSZoning']=df['MSZoning'].astype('category').cat.codes


for i in df.columns:
    df[i]=df[i].astype('category').cat.codes #Kategoorik verilere dönüşüm
    if df[i].isna().sum()!=0:
        df[i].fillna(df[i].mode(),inplace=True) #Eksik veri varsa moduna göre hareket ediliyor
    else:
        if df[i].isna().sum()!=0:
            df[i].fillna(df[i].mean(),inplace=True) #Eksik verilere ortalama alınarak yaklaşılıyor



for i in df_test.columns:
        df_test[i]=df_test[i].astype('category').cat.codes #Kategoorik verilere dönüşüm

        if df_test[i].isna().sum()!=0:
            df_test[i].fillna(df_test[i].mode(),inplace=True) #Eksik veri varsa moduna göre hareket ediliyor
        else:
            if df_test[i].isna().sum()!=0:
                df_test[i].fillna(df_test[i].mean(),inplace=True) #Eksik verilere ortalama alınarak yaklaşılıyor

## 4. MODEL

In [10]:
X_train=df.drop("SalePrice",axis=1)
y_train=df["SalePrice"]

X_pred=df_test

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_pred)

#### 4.1 Hyperparameter

In [12]:
from sklearn.model_selection import cross_validate, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix

In [13]:
regressor = {
    "SGD": SGDRegressor(),
    "KNN": KNeighborsRegressor(), 
    "LR": LogisticRegression(max_iter=1000), 
    "DT": DecisionTreeRegressor(),
    "RF": RandomForestRegressor(max_depth=3, random_state=2),
    "SVM": SVC(),
    "MLP": MLPRegressor(max_iter=1000),
    "XGB": XGBRegressor(),
    "LGBM": LGBMRegressor()
}

results = pd.DataFrame(columns=["Regressor", "rmse", "r2"])
for name, clf in regressor.items():
    model = clf
    clf.fit(X_train_scaled,y_train)
    predictions = clf.predict(X_pred)
    results = results.append({
        "Regressor": name,
        "rmse": np.sqrt(np.square(y_test - predictions)).mean(),
        "r2": 1 - np.square(y_test - predictions).sum()/np.square(y_test - y_test.mean()).sum(),
    }, ignore_index=True)
    
results

NameError: name 'X_test' is not defined

In [ ]:
clf=SGDRegressor()
#clf.fit(X_train_scaled,y_train)

params = {
    'penalty':('l2', 'l1', 'elasticnet'),
    'alpha':(0.0001,0.001,0.00001,0.01),
    'max_iter':(1000,1200,1500,1300),
    'tol': (0.0001,0.001,0.00001,0.01),
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

#Score: 6.63719

In [ ]:
clf=KNeighborsRegressor()
#clf.fit(X_train_scaled,y_train)

params = {
    'n_neighbors':(4,5,6,7,8),
    'algorithm':('auto', 'ball_tree', 'kd_tree', 'brute'),
    'leaf_size':(20,30,40,50),
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)


#Score: 6.56507
#Score: 6.55270 after hyperparameters

In [ ]:
clf=LogisticRegression(max_iter=1000)
#clf.fit(X_train_scaled,y_train)

params = {
    "penalty": ("l1", "l2", "elasticnet"),
    "tol": (0.1, 0.01, 0.001, 0.0001),
    "C": (10.0, 1.0, 0.1, 0.01)
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

#Score: 6.64339

In [ ]:
clf=DecisionTreeRegressor()
#clf.fit(X_train_scaled,y_train)

params = {
    'criterion':('squared_error', 'friedman_mse', 'absolute_error', 'poisson'),
    
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

#Score: 6.56507
#Score: 6.64261 after hyperparameter

In [14]:
clf=RandomForestRegressor(max_depth=3, random_state=2)
#clf.fit(X_train_scaled,y_train)

params = {
    "max_depth": (5,6,7,8),
    'n_estimators':(100,120,150,200,250),
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)



#Score: 6.49849
#Score: 6.56055 after hyperparameter

Best hyperparameter: {'max_depth': 8, 'n_estimators': 150}

In [ ]:
clf=SVC()
#clf.fit(X_train_scaled,y_train)

params = {
    "tol": (0.1, 0.01, 0.001, 0.0001,0.00001),
    "C": (10.0, 1.0, 0.1, 0.01)
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

#Score: 6.62245

In [ ]:
clf=XGBRegressor()
#clf.fit(X_train_scaled,y_train)

params = {
    "learning_rate": (0.1,0.3, 0.01, 0.001, 0.0001,0.00001),
    "max_depth": (5,6,7,8),
    'n_estimators':(100,120,130,150),
    'base_score': (0.1,0.25,0.5,0.6,0.75,0.8,0.9)
}
clf = GridSearchCV(clf, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

#Score: 6.63865

In [ ]:
clf=LGBMRegressor()
clf.fit(X_train_scaled,y_train)
#Score: 6.62111

In [ ]:
clf=MLPRegressor()
clf.fit(X_train_scaled,y_train)
#Score: 6.66096

#### 4.2 Normal Çözüm

In [ ]:
from sklearn.model_selection import cross_validate, GridSearchCV
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVC
from sklearn.neural_network import MLPRegressor
from sklearn.linear_model import SGDRegressor
from sklearn.naive_bayes import GaussianNB
from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from sklearn.metrics import classification_report, accuracy_score, f1_score, confusion_matrix

In [ ]:
regressor = RandomForestRegressor()
params = {
    'max_features':(0.5,1),
    'min_samples_split':(2,10,20),
    'max_depth': (None,1,2,3,4),
    'n_estimators': (50,100,150,200,250,300),
}
clf = GridSearchCV(regressor, params, cv=10)
clf.fit(X_train_scaled, y_train)
print("Best hyperparameter:", clf.best_params_)

In [ ]:
predictions = clf.predict(X_test)


rmse = np.sqrt(np.square(y_test - predictions)).mean()


r2 = 1 - np.square(y_test - predictions).sum()/np.square(y_test - y_test.mean()).sum()

print(f"testing data: root mean squared error = {rmse}\nR-squared = {r2}")

In [ ]:
predictions_train = clf.predict(X_train)

rmse_train = np.sqrt(np.square(y_train - predictions_train)).mean()

r2_train = 1 - np.square(y_train - predictions_train).sum()/np.square(y_train - y_train.mean()).sum()

print(f"training data: root mean squared error = {rmse_train}\nR-squared = {r2_train}")

### Gönderme

In [15]:
y_pred = clf.predict(X_test_scaled)

In [16]:
submission = pd.read_csv("sample_submission.csv")
submission["SalePrice"] = y_pred[:1459]
submission.to_csv('submission.csv', index=False)

In [17]:
!kaggle competitions submit -c house-prices-advanced-regression-techniques -f submission.csv -m ""

Successfully submitted to House Prices - Advanced Regression Techniques

  0%|          | 0.00/34.8k [00:00<?, ?B/s]
 23%|██▎       | 8.00k/34.8k [00:00<00:00, 58.7kB/s]
100%|██████████| 34.8k/34.8k [00:02<00:00, 15.8kB/s]